# Generated by Django 5.1.3 on 2024-12-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='subject',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('login', 'Login'), ('signup', 'Signup'), ('new_post', 'New Post'), ('post_edit', 'Post Edit'), ('post_reaction', 'Post Reaction')], max_length=20, null=True),
        ),
    ]
