# Generated by Django 5.1.3 on 2024-12-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_remove_offer_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='subject',
            field=models.CharField(blank=True, choices=[('all', 'All')], max_length=20, null=True),
        ),
    ]
