# Generated by Django 5.1.3 on 2024-12-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_alter_offer_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='subject',
            field=models.CharField(blank=True, choices=[], max_length=20, null=True),
        ),
    ]
