# Generated by Django 5.1.3 on 2024-12-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumpost_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
