# Generated by Django 5.1.3 on 2024-12-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumpost_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'verbose_name': 'forum_post'},
        ),
    ]
