# Generated by Django 5.1.3 on 2024-12-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='subject',
            field=models.CharField(blank=True, choices=[('new_post', 'New Post'), ('post_reply', 'Post Reply'), ('post_reaction', 'Post Reaction')], max_length=50, null=True),
        ),
    ]
