# Generated by Django 5.1.3 on 2024-12-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_usernotificationsettings_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
