# Generated by Django 5.1.3 on 2024-12-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_notification_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('new_post', 'New Post'), ('post_reply', 'Post Reply'), ('post_reaction', 'Post Reaction')], max_length=20),
        ),
    ]
