# Generated by Django 5.1.3 on 2024-12-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_notificationsubscriber_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('new_post', 'New Post'), ('post_reply', 'Post Reply'), ('post_reaction', 'Post Reaction'), ('login', 'Login'), ('signup', 'Signup')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='subject',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('new_post', 'New Post'), ('post_reply', 'Post Reply'), ('post_reaction', 'Post Reaction'), ('login', 'Login'), ('signup', 'Signup')], default='all', max_length=50, null=True),
        ),
    ]
