# Generated by Django 5.1.3 on 2024-12-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_notification_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='unique_key',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('new_post', 'New Post'), ('post_comment', 'Post Comment'), ('post_reaction', 'Post Reaction'), ('login', 'Login'), ('signup', 'Signup')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='subject',
            field=models.CharField(blank=True, choices=[('new_post', 'New Post'), ('post_comment', 'Post Comment'), ('post_reaction', 'Post Reaction'), ('login', 'Login'), ('signup', 'Signup')], max_length=50, null=True),
        ),
    ]
