# Generated by Django 5.1.3 on 2024-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_usernotificationsettings_unique_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('new_post', 'New Post'), ('post_comment', 'Post Comment'), ('post_reaction', 'Post Reaction'), ('all', 'All'), ('login', 'Login'), ('signup', 'Signup')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotificationsettings',
            name='subject',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('new_post', 'New Post'), ('post_comment', 'Post Comment'), ('post_reaction', 'Post Reaction'), ('all', 'All'), ('login', 'Login'), ('signup', 'Signup')], max_length=50, null=True),
        ),
    ]
