# Generated by Django 5.1.3 on 2024-12-06 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_notification_category_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('login', 'Login'), ('signup', 'Signup'), ('new_post', 'New Post'), ('post_comment', 'Post Comment'), ('post_reaction', 'Post Reaction')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, choices=[('all', 'All'), ('login', 'Login'), ('signup', 'Signup'), ('new_post', 'New Post'), ('post_comment', 'Post Comment'), ('post_reaction', 'Post Reaction')], max_length=50, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('push_notification', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'subject')},
            },
        ),
        migrations.DeleteModel(
            name='UserNotificationSettings',
        ),
    ]
