# Generated by Django 5.1.3 on 2024-12-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_notification_category_usernotificationsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
