# Generated by Django 5.1.3 on 2024-12-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_notification_action_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('json_data', models.JSONField(blank=True, help_text='JSON data for payload.', null=True)),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='The subject of the email.', max_length=255)),
                ('body', models.TextField(help_text='The main content of the email.')),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment.', null=True, upload_to='mail_attachments/')),
                ('sender_email', models.EmailField(help_text='Email address of the sender.', max_length=254)),
                ('recipient_emails', models.TextField(help_text='Comma-separated list of recipient email addresses.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
