# Generated by Django 5.1.3 on 2024-12-09 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_json_data_cloudmessage_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudmessage',
            name='message_id',
        ),
    ]
