# Generated by Django 5.1.3 on 2024-12-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_cloudmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('login', 'Login'), ('signup', 'Signup'), ('new_post', 'New Post'), ('post_edit', 'Post Edit'), ('post_reaction', 'Post Reaction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usernotificationsetting',
            name='subject',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('login', 'Login'), ('signup', 'Signup'), ('new_post', 'New Post'), ('post_edit', 'Post Edit'), ('post_reaction', 'Post Reaction')], max_length=50, null=True),
        ),
    ]
