# Generated by Django 5.1.3 on 2024-12-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_cloudmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmessage',
            name='attachment',
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
