# Generated by Django 5.1.3 on 2024-12-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_mailmessage_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotificationsetting',
            old_name='push_notification',
            new_name='push',
        ),
    ]
