# Generated by Django 5.1.3 on 2024-12-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_notification_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationsetting',
            name='subject',
            field=models.CharField(blank=True, choices=[('new_post', 'New Post'), ('post_edit', 'Post Edit'), ('post_reaction', 'Post Reaction'), ('new_reply', 'New Reply'), ('reply_edit', 'Reply Edit'), ('reply_reaction', 'Reply Reaction'), ('all', 'All'), ('new_offer', 'New Offer'), ('offer_reminder', 'Offer Reminder')], max_length=50, null=True),
        ),
    ]
