# Generated by Django 5.1.3 on 2024-12-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_usernotificationsetting_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='slug',
        ),
    ]
