# Generated by Django 5.1.3 on 2024-12-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_notification_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudmessage',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
