# Generated by Django 5.1.3 on 2024-12-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_cloudmessage_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudmessage',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
